"""Add new fields to user model

Revision ID: 6f59426f05c4
Revises: c03fc8a05015
Create Date: 2023-11-01 11:50:37.318548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f59426f05c4'
down_revision = 'c03fc8a05015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
